algoritmo "semnome"

var

   cont, num:inteiro
inicio

         para cont de 1 ate 5 faca
              escreva("Informe um numero: ")
              leia(num)

              se( num < 0) entao
                  escreval(num," é negativo")
                  escreval("-----------------")
              senao
                  escreval(num," é positivo")
                  escreval("-----------------")
              fimse

         fimpara
         
fimalgoritmo
