algoritmo "semnome"

var

   cont, num:inteiro
inicio

         para cont de 1 ate 5 faca
              escreva("Informe um numero: ")
              leia(num)

              se( num mod 2 = 0)entao
                  escreval(num," é par")
                  escreval("-----------------")
              senao
                  escreval(num," é impar")
                  escreval("-----------------")
              fimse

         fimpara
         
fimalgoritmo
